baseURL = 'https://github.com/jtmlis/jtmlis.github.io'
languageCode = 'en-us'
title = "JTM's blog"
theme = 'ananke'
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
DefaultContentLanguage = "en"

